---
title: "Спецификация проекта"
author: "Anatoly Sorokin"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  html_document: default
  pdf_document:
    keep_tex: yes
    number_sections: yes
header-includes:
- \usepackage[T2A]{fontenc}
- \usepackage[utf8]{inputenc}
- \usepackage[english,russian]{babel}
- \usepackage{grffile}
- \usepackage{rotating}
- \usepackage{caption}
- \usepackage{longtable}
- \usepackage{lscape}
---
# Rkappa проект

Проект Rkappa задумывался как сжатое описание вычислительного эксперимента по вычислению коэффициентов чувствительности и анализа достижимости для rule-based моделей, в частности написанных на языке kappa. В некотором смысле Rkappa можно рассматривать как независимую реализацию SED-ML на каппа. И в будущем планируется построить модуль экспорта проекта в SED-ML.

Основными модулями данных в проекте Rkappa являются:

1. Метаданные
1. Код модели
2. Диапазоны параметров
3. Шаблоны симуляции моделей

В целом проект содержит 16 полей:

* "name" 
* "createDate"
* "constLines"
* "templateLines"
* "replaceRegexp"
* "nRep"
* "nSets"
* "execPath"
* "type"
* "shLines"
* "paramLines"
* "pTable"
* "dateC"
* "seed"
* "paramSets"
* "updateDate"

Разберем структуру и назначение каждого поля более подробно:

## Метаданные

### name
Название проекта, если имя не задано в явном виде при создании проекта, имя будет иметь вид "multi%Y%m%d%H%M%S", где %Y%m%d%H%M%S -- дата и время создания проекта с точностью до секунд.

### createDate 
Дата создания изначальной версии проекта.

### dateC
Дата создания дочернего проекта в фунции *recreate.kproject*.

### updateDate
Дата последнего обновления проекта. Это может быть генерация полной таблицы параметров, расширение таблицы параметров и т.д. Это поле необходимо для контроля того, что версия проекта локальная совпадает с версией проекта на удаленном сервере.

### type
Тип проекта: 'parallel' 'concurrent' 'both'. 

### Необходимые
* note/description -- необязательное поле содержащее описание проекта.

## Код модели
## Диапазоны параметров
### nSets
Число точек в пространстве параметров, которые будут выведены для симуляции. Должно быть меньше либо равно числу строк в таблице paramSets. Если nSets>paramSets, при попытки экспорта проекта в исполняемый фолдер возникнет ошибка. В этом случае дополнительные строки можно создать используя функцию *addSets*.

### pTable"
Таблица диапазонов параметров. 

### seed"
Таблица 
### paramSets"

## Шаблоны симуляции моделей

### Необходимые
* eventNum -- число реакционных событий, которые должны быть просимулированы
* outNum -- число событий, после которого выводится очередная строка в выходной файл

# SessionInfo
```{r sessionInfo}
sessionInfo()
```
